# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: spittet/node-mongodb

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g yarn
          - npm install -g mocha
          - yarn install && cd coin_board && yarn install && cd ..
          - ./INIT_DEV.sh -lt
          - mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=./test-reports/junit.xml
