#    ____              ____   U _____ u  _                  _   _   U _____ u
#  U|  _"\ u  ___    U|  _"\ u\| ___"|/ |"|        ___     | \ |"|  \| ___"|/
#  \| |_) |/ |_"_|   \| |_) |/ |  _|" U | | u     |_"_|   <|  \| |>  |  _|"
#   |  __/    | |     |  __/   | |___  \| |/__     | |    U| |\  |u  | |___
#   |_|     U/| |\u   |_|      |_____|  |_____|  U/| |\u   |_| \_|   |_____|
#   ||>>_.-,_|___|_,-.||>>_    <<   >>  //  \\.-,_|___|_,-.||   \\,-.<<   >>
#  (__)__)\_)-' '-(_/(__)__)  (__) (__)(_")("_)\_)-' '-(_/ (_")  (_/(__) (__)
# ## COINBO4RD
#
# Notes :
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g yarn
          - npm install -g mocha
          - yarn install && cd coin_board && yarn install && cd ..
          - cd .. && pwd && ls -la && ./INIT_DEV.sh -lt
          - mocha test/*/*.js --reporter mocha-junit-reporter --reporter-options mochaFile=./test-reports/junit.xml
        services:
          - mongo

definitions:
  services:
    mongo:
      image: mongo
